package:
    name: pynio
    version: 1.5.0beta

source:
    git_url: https://github.com/NCAR/pynio.git
    git_tag: master

build:
    number: 2
    skip: True  # [win or py3k]

requirements:
    build:
        - python
        - numpy x.x
        - libpng
        - jasper
        - jpeg
        - zlib
        - hdf4
        - hdf5 1.8.15.1
        - libnetcdf
        - proj.4
        - gdal 1.11.4
        - curl
        - libiconv
        - g2clib
        - hdfeos2
        - hdfeos5 5.1.15 0
        - gcc
    run:
        - python
        - numpy x.x
        - libpng
        - jasper
        - jpeg
        - zlib
        - libnetcdf
        - hdf4
        - hdf5 1.8.15.1
        - proj.4
        - gdal 1.11.4
        - curl
        - libiconv
        - g2clib
        - hdfeos2
        - hdfeos5  5.1.15 0
        - krb5
        - libgcc

test:
    requires:
        - nose
    imports:
        - Nio
    commands:
        - cd $SRC_DIR/test && nosetests
        - conda inspect linkages -n _test pynio  # [linux]

about:
    home: http://www.pyngl.ucar.edu/Nio.shtml
    license: BSD-3-clause
    summary: PyNIO is a multi-format data I/O package with a NetCDF-style interface

extra:
    recipe-maintainers:
        - ocefpaf
        - jhamman
