{% set version = "1.5.0" %}
{% set beta = "beta20160623" %}

package:
    name: pynio
    version: {{ version }}

source:
    fn: pynio-{{ version }}-{{ beta }}.tar.gz
    url: https://github.com/NCAR/pynio/archive/{{ version }}_{{ beta }}.tar.gz
    sha256: 43411c577e21335d4684f384cbf117b41202f55b49198d1c688fc65703dbff68

build:
    number: 7
    skip: True  # [win or py3k]
    detect_binary_files_with_prefix: true

requirements:
    build:
        - python
        - numpy x.x
        - libnetcdf 4.4.*
        - proj.4
        - gdal 1.11.*
        - g2clib
        - hdfeos2
        - hdfeos5
        - gcc
    run:
        - python
        - numpy x.x
        - libnetcdf 4.4.*
        - hdf4
        - proj.4
        - gdal 1.11.*
        - g2clib
        - hdfeos2
        - hdfeos5
        - libgcc

test:
    requires:
        - nose
    imports:
        - Nio
    commands:
        - cd $SRC_DIR/test && nosetests
        - conda inspect linkages -n _test pynio  # [linux]

about:
    home: http://www.pyngl.ucar.edu/Nio.shtml
    license: BSD-3-clause
    summary: PyNIO is a multi-format data I/O package with a NetCDF-style interface

extra:
    recipe-maintainers:
        - ocefpaf
        - jhamman
