{% set version = "1.5.0beta" %}
{% set commit = "0f6c6896997a56c4c69ad3b3ce01060eab4d7576" %}

package:
    name: pynio
    version: {{ version }}

source:
    fn: {{ commit }}.tar.gz
    url: https://github.com/NCAR/pynio/archive/{{ commit }}.tar.gz
    sha256: becd7ce9f5c8ccb98d5b0ae538ee0cd051eb9d89d918628183fe5c5038a0ec12

build:
    number: 6
    skip: True  # [win or py3k]

requirements:
    build:
        - python
        - numpy x.x
        - libnetcdf 4.4.*
        - proj.4
        - gdal 1.11.4
        - g2clib
        - hdfeos2
        - hdfeos5
        - gcc
    run:
        - python
        - numpy x.x
        - libnetcdf 4.4.*
        - hdf4
        - proj.4
        - gdal 1.11.4
        - g2clib
        - hdfeos2
        - hdfeos5
        - libgcc

test:
    requires:
        - nose
    imports:
        - Nio
    commands:
        - cd $SRC_DIR/test && nosetests
        - conda inspect linkages -n _test pynio  # [linux]

about:
    home: http://www.pyngl.ucar.edu/Nio.shtml
    license: BSD-3-clause
    summary: PyNIO is a multi-format data I/O package with a NetCDF-style interface

extra:
    recipe-maintainers:
        - ocefpaf
        - jhamman
