travis:
  secure:
    BINSTAR_TOKEN: WVSd+2NnkWcvjXXNYiXBITKWj8d8FaZcgPhY7aabbhGe1GqJlLLRmCMfhzeuB7r8iN0oKmtdVfVrph030q61HSDnwsS3/dif19l+DJdvOf3iqZBAkVDZm7lERpEBEjulwdAqCb4lU3tl/dLm/3G9AG6eiZT8zcgy2BdSBQRtyFxDDfby5gcrMwXw3rNpDTmyxXyWgrcz3rymvJm/gGlP6bBz5fYCd3qI68/0TAhLx9nzl/7v++uNcGI3eI1kl8Lu5W95b2ZGTxq9zMouY3oUcUkaDVnFcf/Hx65qd1WU/cksON6tsh1VKOOz2PLm/gAZNCrXphOE/+GkRPqcNpRyTgroUMcIwDq7nPON46LCBB4DIVg0ANRYXwgVgUp723Hl1asi+oXvpZqkvb5ezixm+hUrFiyW0Bc3RvGJb1DRVrSitKjGpZKgPduZiAvBhhaitZ0n1lav9AJzdZ75td3iuVMcXxzKSSP6VkJaK0V5WOQddFSdJQCl4bqXhaAsomc+7NgplNNPTwHueQcPTJ/Ea0Q+BqLQO692p6vdOfOqXXYeZbzEud310jrcCZ8VQDbulOff4H+hyVBKK6wlvyJMLSW6TeZuX+MvlDr0Iz1IRLrSBfn6CufwvlN+XP8gJTSGe6+E6s0mNbOP0qmcQkeenz86utrFv4SP8JRiCLX1W1g=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
